---
functional:
  - Решение задачи на скорость против другого игрока. Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения.
  - В игру можно играть с любым человеком, с ботом или другом по ссылке.
  - Можно выбрать игру по уровню сложности elementary, easy, medium, hard. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад.
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - Чат для зарегистрированных пользователей
  - Чат для каждой игры
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Исходы игры выиграл, проиграл, сдался
  - Всплывающие сообщения о результате проверки и выигрыше игрока
  - Страница ожидания игрока
  - авторизация через github
  - страница со списком игр
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - регистрация на сайте
  - личный кабинет
